services:
  - type: web
    name: rps-royale-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: cd ../client && npm install && npm run build:render && cd ../server && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DISCORD_CLIENT_ID
        value: "1549787463642517516"
      - key: DISCORD_CLIENT_SECRET
        sync: false
